"""
Django settings for weblog project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from utils.exception_handler import  custom_exception_handler
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e&a6w3tn*g(+716r*(!2fu()qj!6v95ask)@bb4p!81+g07lql'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "user",
    'home',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',


]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
]

ROOT_URLCONF = 'weblog.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'weblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL 引擎
        'NAME': 'myblog',  # 数据库名（必须和步骤 2 创建的一致）
        'USER': 'root',  # MySQL 用户名
        'PASSWORD': 'zll200205',  # MySQL 密码
        'HOST': 'localhost',  # 数据库地址（本地为 localhost，服务器填服务器IP）
        'PORT': '3306',  # MySQL 端口（默认 3306）
        'OPTIONS': {
            'charset': 'utf8mb4',  # 字符集（支持表情符号）
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 原 'en-us' 改为中文

# 时区配置：中国标准时间（核心配置，已正确）
TIME_ZONE = 'Asia/Shanghai'

# 国际化支持：保持开启（不影响时区，仅支持多语言）
USE_I18N = True

# 时区支持：必须开启（关键！否则 TIME_ZONE 不生效）
USE_TZ = True  # 无需修改，保持 True 即可

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # Vue前端本地地址（必须写完整，带协议和端口）
    "http://127.0.0.1:8080",
]
# 允许前端携带 Cookie（如果需要记住登录状态，可选）
CORS_ALLOW_CREDENTIALS = False
# DRF 全局配置
REST_FRAMEWORK = {
    # 1. 禁用 DRF 浏览界面（仅返回 JSON）
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],

    # 2. 默认认证方式：JWT 认证（元组内仅放认证类）
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 3. 自定义异常处理器（顶级键值对，路径正确）
    'EXCEPTION_HANDLER': 'utils.exception_handler.custom_exception_handler',

    # 4. 限流配置（顶级键值对）
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',
        'user': '30/minute'
    },
}

# JWT 令牌配置（可自定义过期时间等）
from datetime import timedelta
SIMPLE_JWT = {
    # 访问令牌（access_token）过期时间：30分钟（开发环境可设长点，生产环境建议15-30分钟）
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=500),
    # 刷新令牌（refresh_token）过期时间：7天（用于刷新访问令牌，避免重复登录）
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # 令牌前缀（前端请求时需在请求头加：Authorization: Bearer <token>）
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',  # 必须与用户模型的主键字段一致（你的模型主键是id，所以配置为'id'）
    'USER_ID_CLAIM': 'user_id',
}

# 关键：确保之前配置了自定义用户模型（如果没配置，先添加！）
# 必须和 user/models.py 中的 User 模型对应
AUTH_USER_MODEL = 'user.User'
# 跨域配置：允许前端地址访问后端接口
# weblog/settings.py（末尾添加）
# 强制验证 DRF 配置是否被正确加载
from rest_framework.settings import api_settings
# 打印配置（启动服务器时会在命令行输出，用于验证）
# print("="*50)
# print("DRF 全局配置加载结果：")
# print(f"DEFAULT_RENDERER_CLASSES: {api_settings.DEFAULT_RENDERER_CLASSES}")
# print(f"EXCEPTION_HANDLER: {api_settings.EXCEPTION_HANDLER}")
# print(f"DEFAULT_THROTTLE_CLASSES: {api_settings.DEFAULT_THROTTLE_CLASSES}")
# print("="*50)
CORS_ALLOW_ALL_ORIGINS = True
# 允许所有请求头（包括Authorization）
CORS_ALLOW_HEADERS = ['*']
MEDIA_URL = '/media/'  # 前端访问头像的URL前缀（如：http://xxx.com/media/avatars/123.jpg）
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 本地存储路径（项目根目录/media文件夹）

# 允许的图片上传格式（安全限制）
ALLOWED_UPLOAD_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif']
MAX_UPLOAD_SIZE = 5 * 1024 * 1024  # 最大5MB